version: '3.7'

volumes:
  docker-registry: {}
  gcr-registry: {}
  quay-registry: {}
  k8sio-registry: {}
  k8sgcr-registry: {}
  ghcr-registry: {}
  gitlab-registry: {}

services:

  caddy:
    restart: always
    image: caddy
    ports:
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile 
      - ./data/caddy:/data

  docker:
    restart: always
    image: registry:2.8
    volumes:
      - ./config/docker.yml:/etc/docker/registry/config.yml:ro
      - docker-registry:/var/lib/registry:rw

  k8sio:
    restart: always
    image: registry:2.8
    volumes:
      - ./config/k8sio.yml:/etc/docker/registry/config.yml:ro
      - k8sio-registry:/var/lib/registry:rw

  k8sgcr:
    restart: always
    image: registry:2.8
    volumes:
      - ./config/k8sgcr.yml:/etc/docker/registry/config.yml:ro
      - k8sgcr-registry:/var/lib/registry:rw

  gcr:
    restart: always
    image: registry:2.8
    volumes:
      - ./config/gcr.yml:/etc/docker/registry/config.yml:ro
      - gcr-registry:/var/lib/registry:rw

  quay:
    restart: always
    image: registry:2.8
    volumes:
      - ./config/quay.yml:/etc/docker/registry/config.yml:ro
      - quay-registry:/var/lib/registry:rw

  ghcr:
    restart: always
    image: registry:2.8
    volumes:
      - ./config/ghcr.yml:/etc/docker/registry/config.yml:ro
      - ghcr-registry:/var/lib/registry:rw

  gitlab:
    restart: always
    image: registry:2.8
    volumes:
      - ./config/gitlab.yml:/etc/docker/registry/config.yml:ro
      - gitlab-registry:/var/lib/registry:rw