version: '3.7'

volumes:
  docker-registry: {}
  gcr-registry: {}
  quay-registry: {}
  k8s-registry: {}
  gitlab-registry: {}

services:

  caddy:
    restart: always
    image: caddy
    ports:
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile 
      - ./data/caddy:/data

  docker:
    restart: always
    image: registry
    volumes:
      - ./config/docker.yml:/etc/docker/registry/config.yml:ro
      - docker-registry:/var/lib/registry:rw

  gcr:
    restart: always
    image: registry
    volumes:
      - ./config/gcr.yml:/etc/docker/registry/config.yml:ro
      - gcr-registry:/var/lib/registry:rw

  quay:
    restart: always
    image: registry
    volumes:
      - ./config/quay.yml:/etc/docker/registry/config.yml:ro
      - quay-registry:/var/lib/registry:rw

  k8s:
    restart: always
    image: registry
    volumes:
      - ./config/k8s.yml:/etc/docker/registry/config.yml:ro
      - k8s-registry:/var/lib/registry:rw

  gitlab:
    restart: always
    image: registry
    volumes:
      - ./config/gitlab.yml:/etc/docker/registry/config.yml:ro
      - gitlab-registry:/var/lib/registry:rw